apiVersion: v1
entries:
  kubefed:
  - apiVersion: v1
    created: "2020-02-27T23:59:03.144808776Z"
    description: KubeFed helm chart
    digest: e4e1c151f39101db63eb69cefc593d01010d75d8c0b46b4b9a13c7f8dc3594bb
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.2.0-alpha.1/kubefed-0.2.0-alpha.1.tgz
    version: 0.2.0-alpha.1
