apiVersion: v1
entries:
  kubefed:
  - apiVersion: v1
    created: 2019-08-16T20:55:41.543976601-07:00
    description: KubeFed helm chart
    digest: e538f9ea432865d957d842442938dc926a54e4b462996d0600d9e4d9405ced4c
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.1.0-rc6/kubefed-0.1.0-rc6.tgz
    version: 0.1.0-rc6
  - apiVersion: v1
    created: 2019-08-01T08:42:00.481443895-07:00
    description: KubeFed helm chart
    digest: d279fabdc3a774d1d40ba4589f39cc0642f932c721ea5aba869648f3574b1371
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.1.0-rc5/kubefed-0.1.0-rc5.tgz
    version: 0.1.0-rc5
  - apiVersion: v1
    created: 2019-07-19T16:38:49.749571917-07:00
    description: KubeFed helm chart
    digest: c889fb71e5c426521a7e7b48d0d32aa3c0ddf907c3b3139a236828251b5e3b2e
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.1.0-rc4/kubefed-0.1.0-rc4.tgz
    version: 0.1.0-rc4
  - apiVersion: v1
    created: 2019-06-24T17:28:35.280013854-07:00
    description: KubeFed helm chart
    digest: de65ef0d2564777486b824211e9ce1a0154bd4480ed1be08dc9d0266f71aeea9
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.1.0-rc3/kubefed-0.1.0-rc3.tgz
    version: 0.1.0-rc3
  - apiVersion: v1
    created: 2019-05-27T07:35:43.256767346-07:00
    description: KubeFed helm chart
    digest: aa3a543f363c97a8774d970dde615f55afda6a28d168a2d33844fb52687d7cb7
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.1.0-rc2/kubefed-0.1.0-rc2.tgz
    version: 0.1.0-rc2
  - apiVersion: v1
    created: 2019-05-22T15:59:04.160292519-07:00
    description: KubeFed helm chart
    digest: 4f829657ea2088c176869d8e65435926b59f5cf1f7f1ce0102fae3a81c576d5e
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.1.0-rc1/kubefed-0.1.0-rc1.tgz
    version: 0.1.0-rc1
generated: 2019-08-16T20:55:41.543098393-07:00
